language: python

os:
  - linux
  - osx

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - python -m pytest papis --cov=papis

install:
  - pip install setuptools
  - pip install python-coveralls
  - pip install -e .[develop]
  - pip install -e .[optional]
  - make install
  #- sudo apt-get update -qq
  #- sudo apt-get install -y git

after_success:
  - coveralls
