language: python

os:
  - linux

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

script:
  - make test

install:
  - pip install setuptools
  - pip install -e .[develop]
  - pip install pytest
  - make install
